// <auto-generated />
using System;
using GamingCorner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingCorner.Data.Migrations
{
    [DbContext(typeof(GamingCornerContext))]
    [Migration("20240902192747_migration2_09")]
    partial class migration2_09
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GamingCorner.Models.Console_", b =>
                {
                    b.Property<int>("ConsoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsoleId"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ConsoleId");

                    b.HasIndex("PlatformId");

                    b.ToTable("Consoles");

                    b.HasData(
                        new
                        {
                            ConsoleId = 1,
                            Available = true,
                            ImageURL = "",
                            Name = "Play Station 4",
                            PlatformId = 1,
                            Price = 300m,
                            Specifications = "Ta bien",
                            Stock = 16
                        },
                        new
                        {
                            ConsoleId = 2,
                            Available = true,
                            ImageURL = "",
                            Name = "Xbox 360",
                            PlatformId = 3,
                            Price = 265m,
                            Specifications = "Ta bien pero no tanto",
                            Stock = 5
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            Name = "RPG"
                        },
                        new
                        {
                            GenderId = 2,
                            Name = "Shooter"
                        },
                        new
                        {
                            GenderId = 3,
                            Name = "Estrategia"
                        },
                        new
                        {
                            GenderId = 4,
                            Name = "Accion"
                        },
                        new
                        {
                            GenderId = 5,
                            Name = "Deportes"
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlatformId");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            PlatformId = 1,
                            Name = "Steam"
                        },
                        new
                        {
                            PlatformId = 2,
                            Name = "Play Station"
                        },
                        new
                        {
                            PlatformId = 3,
                            Name = "Xbox"
                        },
                        new
                        {
                            PlatformId = 4,
                            Name = "Switch"
                        },
                        new
                        {
                            PlatformId = 5,
                            Name = "Ubisoft"
                        },
                        new
                        {
                            PlatformId = 6,
                            Name = "Epic Games"
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Available = true,
                            Description = "COD BO4 nuevo en perfectas condiciones",
                            ImageURL = "",
                            Name = "COD nuevo",
                            Price = 15m
                        },
                        new
                        {
                            ProductId = 2,
                            Available = true,
                            Description = "Juego casi nuevo",
                            ImageURL = "",
                            Name = "Uncharted",
                            Price = 10m
                        },
                        new
                        {
                            ProductId = 3,
                            Available = true,
                            Description = "Practicamente nuevo",
                            ImageURL = "",
                            Name = "Dark Souls",
                            Price = 7m
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"), 1L, 1);

                    b.Property<int?>("ConsoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VideogameId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("ConsoleId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("VideogameId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Date = new DateTime(2024, 9, 2, 21, 27, 47, 730, DateTimeKind.Local).AddTicks(293),
                            ProductId = 1,
                            Type = "Compra",
                            UserId = 1
                        },
                        new
                        {
                            TransactionId = 2,
                            Date = new DateTime(2024, 9, 2, 21, 27, 47, 730, DateTimeKind.Local).AddTicks(328),
                            ProductId = 2,
                            Type = "Compra",
                            UserId = 2
                        },
                        new
                        {
                            TransactionId = 3,
                            Date = new DateTime(2024, 9, 2, 21, 27, 47, 730, DateTimeKind.Local).AddTicks(330),
                            ProductId = 3,
                            Type = "Compra",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "C/ La Lectura",
                            Admin = true,
                            Email = "diego@gmail.com",
                            ImageURL = "",
                            Name = "Diego",
                            Password = "12345",
                            PhoneNumber = "601112734"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "Avda. San Juan de la Peña",
                            Admin = true,
                            Email = "ivan@gmail.com",
                            ImageURL = "",
                            Name = "Ivan",
                            Password = "12345",
                            PhoneNumber = "123456789"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "El Actur",
                            Admin = false,
                            Email = "adrian@gmail.com",
                            ImageURL = "",
                            Name = "Adrian",
                            Password = "00000",
                            PhoneNumber = "987654321"
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Videogame", b =>
                {
                    b.Property<int>("VideogameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideogameId"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pegi")
                        .HasColumnType("int");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Requisitos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("VideogameId");

                    b.HasIndex("GenderId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("UserId");

                    b.ToTable("Videogames");

                    b.HasData(
                        new
                        {
                            VideogameId = 1,
                            Available = true,
                            Description = "Altos carros voladores",
                            GenderId = 1,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co5w0w.webp",
                            Name = "Rocket League",
                            Pegi = 12,
                            PlatformId = 1,
                            Price = 15m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 3,
                            UserId = 1
                        },
                        new
                        {
                            VideogameId = 2,
                            Available = true,
                            Description = "Gran Robo de Autos",
                            GenderId = 2,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1twh.webp",
                            Name = "GTA 5",
                            Pegi = 18,
                            PlatformId = 2,
                            Price = 13m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 7,
                            UserId = 1
                        },
                        new
                        {
                            VideogameId = 3,
                            Available = true,
                            Description = "Aventura épica en un mundo de fantasía",
                            GenderId = 3,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lgo.webp",
                            Name = "The Witcher 3",
                            Pegi = 18,
                            PlatformId = 3,
                            Price = 20m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 5,
                            UserId = 2
                        },
                        new
                        {
                            VideogameId = 4,
                            Available = true,
                            Description = "Juego de construcción y aventuras",
                            GenderId = 4,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co2b4k.webp",
                            Name = "Minecraft",
                            Pegi = 7,
                            PlatformId = 1,
                            Price = 25m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 10,
                            UserId = 3
                        },
                        new
                        {
                            VideogameId = 5,
                            Available = true,
                            Description = "Juego de supervivencia y construcción",
                            GenderId = 5,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ekt.webp",
                            Name = "Fortnite",
                            Pegi = 12,
                            PlatformId = 2,
                            Price = 0m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 8,
                            UserId = 2
                        },
                        new
                        {
                            VideogameId = 6,
                            Available = true,
                            Description = "Juego de disparos en equipo",
                            GenderId = 1,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co7v86.webp",
                            Name = "Overwatch",
                            Pegi = 12,
                            PlatformId = 3,
                            Price = 30m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 6,
                            UserId = 1
                        },
                        new
                        {
                            VideogameId = 7,
                            Available = true,
                            Description = "Simulación de fútbol",
                            GenderId = 2,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wm2.webp",
                            Name = "FIFA 21",
                            Pegi = 3,
                            PlatformId = 1,
                            Price = 50m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 12,
                            UserId = 2
                        },
                        new
                        {
                            VideogameId = 8,
                            Available = true,
                            Description = "Aventura en un mundo futurista",
                            GenderId = 3,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co64re.webp",
                            Name = "Cyberpunk 2077",
                            Pegi = 18,
                            PlatformId = 2,
                            Price = 60m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 4,
                            UserId = 3
                        },
                        new
                        {
                            VideogameId = 9,
                            Available = true,
                            Description = "Aventura en el Viejo Oeste",
                            GenderId = 4,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.webp",
                            Name = "Red Dead Redemption 2",
                            Pegi = 18,
                            PlatformId = 3,
                            Price = 40m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 9,
                            UserId = 3
                        },
                        new
                        {
                            VideogameId = 10,
                            Available = true,
                            Description = "Aventura de vikingos",
                            GenderId = 5,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rrw.webp",
                            Name = "Assassin's Creed Valhalla",
                            Pegi = 18,
                            PlatformId = 4,
                            Price = 55m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 7,
                            UserId = 1
                        },
                        new
                        {
                            VideogameId = 11,
                            Available = true,
                            Description = "Juego de disparos en primera persona",
                            GenderId = 1,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rsg.webp",
                            Name = "Call of Duty: Modern Warfare",
                            Pegi = 18,
                            PlatformId = 4,
                            Price = 50m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 11,
                            UserId = 1
                        },
                        new
                        {
                            VideogameId = 12,
                            Available = true,
                            Description = "Aventura en un mundo postapocalíptico",
                            GenderId = 2,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co2una.webp",
                            Name = "Horizon Zero Dawn",
                            Pegi = 16,
                            PlatformId = 4,
                            Price = 35m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 5,
                            UserId = 2
                        },
                        new
                        {
                            VideogameId = 13,
                            Available = true,
                            Description = "Simulación de granja",
                            GenderId = 3,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/xrpmydnu9rpxvxfjkiu7.webp",
                            Name = "Stardew Valley",
                            Pegi = 7,
                            PlatformId = 4,
                            Price = 20m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 8,
                            UserId = 2
                        },
                        new
                        {
                            VideogameId = 14,
                            Available = true,
                            Description = "Juego de deducción social",
                            GenderId = 4,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co6kqt.webp",
                            Name = "Among Us",
                            Pegi = 10,
                            PlatformId = 1,
                            Price = 5m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 15,
                            UserId = 2
                        },
                        new
                        {
                            VideogameId = 15,
                            Available = true,
                            Description = "Aventura en el mundo de Hyrule",
                            GenderId = 5,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_small/co4n26.png",
                            Name = "The Legend of Zelda: Breath of the Wild",
                            Pegi = 12,
                            PlatformId = 2,
                            Price = 60m,
                            Requisitos = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 6,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Console_", b =>
                {
                    b.HasOne("GamingCorner.Models.Platform", "Platform")
                        .WithMany("Consoles")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GamingCorner.Models.Transaction", b =>
                {
                    b.HasOne("GamingCorner.Models.Console_", "Console")
                        .WithMany("Transactions")
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamingCorner.Models.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamingCorner.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GamingCorner.Models.Videogame", "Videogame")
                        .WithMany("Transactions")
                        .HasForeignKey("VideogameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Console");

                    b.Navigation("Product");

                    b.Navigation("User");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("GamingCorner.Models.Videogame", b =>
                {
                    b.HasOne("GamingCorner.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingCorner.Models.Platform", "Platform")
                        .WithMany("videogames")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GamingCorner.Models.User", "User")
                        .WithMany("Videogames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Gender");

                    b.Navigation("Platform");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamingCorner.Models.Console_", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GamingCorner.Models.Platform", b =>
                {
                    b.Navigation("Consoles");

                    b.Navigation("videogames");
                });

            modelBuilder.Entity("GamingCorner.Models.Product", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GamingCorner.Models.User", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("Videogames");
                });

            modelBuilder.Entity("GamingCorner.Models.Videogame", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
