// <auto-generated />
using System;
using GamingCorner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingCorner.Data.Migrations
{
    [DbContext(typeof(GamingCornerContext))]
    [Migration("20250602183106_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GamingCorner.Models.Basket", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("GamingCorner.Models.Console", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Generation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrincipalImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Consoles");
                });

            modelBuilder.Entity("GamingCorner.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            Name = "RPG"
                        },
                        new
                        {
                            GenderId = 2,
                            Name = "Shooter"
                        },
                        new
                        {
                            GenderId = 3,
                            Name = "Estrategia"
                        },
                        new
                        {
                            GenderId = 4,
                            Name = "Accion"
                        },
                        new
                        {
                            GenderId = 5,
                            Name = "Deportes"
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("GamingCorner.Models.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("System")
                        .HasColumnType("int");

                    b.HasKey("PlatformId");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            PlatformId = 1,
                            Name = "Steam",
                            System = 0
                        },
                        new
                        {
                            PlatformId = 2,
                            Name = "Play Station",
                            System = 0
                        },
                        new
                        {
                            PlatformId = 3,
                            Name = "Xbox",
                            System = 0
                        },
                        new
                        {
                            PlatformId = 4,
                            Name = "Switch",
                            System = 0
                        },
                        new
                        {
                            PlatformId = 5,
                            Name = "Ubisoft",
                            System = 0
                        },
                        new
                        {
                            PlatformId = 6,
                            Name = "Epic Games",
                            System = 0
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("PlatformId")
                        .HasColumnType("int");

                    b.Property<int?>("Sales")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlatformId = 1,
                            Sales = 50
                        },
                        new
                        {
                            Id = 2,
                            PlatformId = 2,
                            Sales = 44
                        },
                        new
                        {
                            Id = 3,
                            PlatformId = 4,
                            Sales = 22
                        },
                        new
                        {
                            Id = 4,
                            PlatformId = 5,
                            Sales = 4
                        },
                        new
                        {
                            Id = 5,
                            PlatformId = 1,
                            Sales = 141
                        },
                        new
                        {
                            Id = 6,
                            PlatformId = 6,
                            Sales = 967
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.SecondHandProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("SecondHandProducts");
                });

            modelBuilder.Entity("GamingCorner.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "C/ La Lectura",
                            Admin = true,
                            Avatar = "",
                            DateCreated = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "diego@gmail.com",
                            Name = "Diego",
                            Password = "12345",
                            PhoneNumber = "601112734",
                            Rol = 1,
                            State = 1
                        },
                        new
                        {
                            UserId = 2,
                            Address = "Avda. San Juan de la Peña",
                            Admin = true,
                            Avatar = "",
                            DateCreated = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "ivan@gmail.com",
                            Name = "Ivan",
                            Password = "12345",
                            PhoneNumber = "123456789",
                            Rol = 1,
                            State = 1
                        },
                        new
                        {
                            UserId = 3,
                            Address = "El Actur",
                            Admin = false,
                            Avatar = "",
                            DateCreated = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "adrian@gmail.com",
                            Name = "Adrian",
                            Password = "00000",
                            PhoneNumber = "987654321",
                            Rol = 1,
                            State = 1
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Videogame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Distributor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pegi")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrincipalImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Requisitos1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requisitos2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Videogames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Juego de rol y acción en mundo abierto",
                            Developer = "FromSoftware",
                            Discount = 0,
                            Distributor = "Bandai Namco",
                            Name = "Elden Ring",
                            Pegi = 18,
                            Price = 59.99m,
                            PrincipalImageURL = "https://upload.wikimedia.org/wikipedia/en/9/9c/Elden_Ring_Box_art.jpg",
                            ProductId = 1,
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Requisitos1 = "Intel Core i5-8400 / AMD Ryzen 3 3300X",
                            Requisitos2 = "12 GB RAM, GTX 1060 3GB / Radeon RX 580",
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Acción y aventura con mitología nórdica",
                            Developer = "Santa Monica Studio",
                            Discount = 5,
                            Distributor = "Sony Interactive Entertainment",
                            Name = "God of War Ragnarök",
                            Pegi = 18,
                            Price = 69.99m,
                            PrincipalImageURL = "https://upload.wikimedia.org/wikipedia/en/9/9e/God_of_War_Ragnar%C3%B6k_cover.jpg",
                            ProductId = 2,
                            ReleaseDate = new DateTime(2022, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 75
                        },
                        new
                        {
                            Id = 3,
                            Description = "RPG ambientado en el mundo de Harry Potter",
                            Developer = "Portkey Games",
                            Discount = 10,
                            Distributor = "Warner Bros. Games",
                            Name = "Hogwarts Legacy",
                            Pegi = 16,
                            Price = 49.99m,
                            PrincipalImageURL = "https://upload.wikimedia.org/wikipedia/en/7/76/Hogwarts_Legacy_cover.jpg",
                            ProductId = 3,
                            ReleaseDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Requisitos1 = "Intel Core i5-6600 / AMD Ryzen 5 1400",
                            Requisitos2 = "16 GB RAM, GTX 1070 / RX Vega 56",
                            Stock = 80
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.VideogameGender", b =>
                {
                    b.Property<int>("VideogameId")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.HasKey("VideogameId", "GenderId");

                    b.HasIndex("GenderId");

                    b.ToTable("VideogameGenders");
                });

            modelBuilder.Entity("GamingCorner.Models.Basket", b =>
                {
                    b.HasOne("GamingCorner.Models.Product", "Product")
                        .WithMany("Baskets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingCorner.Models.User", "User")
                        .WithMany("Baskets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamingCorner.Models.Console", b =>
                {
                    b.HasOne("GamingCorner.Models.Product", "Product")
                        .WithOne("Console")
                        .HasForeignKey("GamingCorner.Models.Console", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GamingCorner.Models.OrderHeader", b =>
                {
                    b.HasOne("GamingCorner.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamingCorner.Models.Product", b =>
                {
                    b.HasOne("GamingCorner.Models.Platform", "Platform")
                        .WithMany("products")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GamingCorner.Models.SecondHandProduct", b =>
                {
                    b.HasOne("GamingCorner.Models.Product", "Product")
                        .WithOne("SecondHandProduct")
                        .HasForeignKey("GamingCorner.Models.SecondHandProduct", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GamingCorner.Models.Videogame", b =>
                {
                    b.HasOne("GamingCorner.Models.Product", "Product")
                        .WithOne("Videogame")
                        .HasForeignKey("GamingCorner.Models.Videogame", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GamingCorner.Models.VideogameGender", b =>
                {
                    b.HasOne("GamingCorner.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingCorner.Models.Videogame", "Videogame")
                        .WithMany("VideogameGenders")
                        .HasForeignKey("VideogameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("GamingCorner.Models.Platform", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("GamingCorner.Models.Product", b =>
                {
                    b.Navigation("Baskets");

                    b.Navigation("Console");

                    b.Navigation("SecondHandProduct");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("GamingCorner.Models.User", b =>
                {
                    b.Navigation("Baskets");
                });

            modelBuilder.Entity("GamingCorner.Models.Videogame", b =>
                {
                    b.Navigation("VideogameGenders");
                });
#pragma warning restore 612, 618
        }
    }
}
