// <auto-generated />
using System;
using GamingCorner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingCorner.Data.Migrations
{
    [DbContext(typeof(GamingCornerContext))]
    [Migration("20250521145750_InitialCreate4")]
    partial class InitialCreate4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GamingCorner.Models.Console", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrincipalImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Consoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Sony",
                            Description = "Consola muy buena",
                            Discount = 50,
                            Name = "Play Station 4",
                            Price = 300m,
                            PrincipalImageURL = "https://gmedia.playstation.com/is/image/SIEPDC/ps4-pro-product-thumbnail-01-en-14sep21",
                            ProductId = 4,
                            ReleaseDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Specifications = "CPU:AMD 'Jaguar' x86-64, 8 núcleos; GPU: motor gráfico AMD de 1,84 TFLOPS basado en Radeon; Memoria:8 GB GDDR5; Almacenamiento:1 TB; Peso: Aprox. 2,1 Kg; Entrada/Salida:2 puertos de altísima velocidad USB (USB 3.1 Gen1) y 1 puerto AUX; Red:1 puerto Ethernet (10BASE-T, 100BASE-TX, 1000BASE-T) / IEEE 802.11 a/b/g/n/ac / Bluetooth® 4.0; Alimentacion:AC de 100-240 V, 50/60 Hz; Consumo de energia: 165W; Salida AV:Salida HDMI™ (compatible con salida HDR)",
                            Stock = 16
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Sony",
                            Description = "Consola  buena",
                            Discount = 10,
                            Name = "Play Station 5",
                            Price = 490m,
                            PrincipalImageURL = "https://m.media-amazon.com/images/I/51f6iZlNnvL.jpg",
                            ProductId = 5,
                            ReleaseDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Specifications = "CPU: AMD Ryzen Zen 2, 8 núcleos a 3.5GHz; GPU: AMD RDNA 2, 10.28 TFLOPs, 36 CUs a 2.23GHz; Memoria: 16 GB GDDR6; Almacenamiento: SSD personalizado de 825 GB; Peso: Aprox. 4.5 Kg; Entrada/Salida: 2 puertos USB de alta velocidad (USB 3.1 Gen2), 1 puerto USB-C; Red: 1 puerto Ethernet (10BASE-T, 100BASE-TX, 1000BASE-T), Wi-Fi 6 (802.11ax), Bluetooth® 5.1; Alimentación: AC 100-240V, 50/60Hz; Consumo de energía: 350W; Salida AV: Salida HDMI™ 2.1 (compatible con 4K a 120Hz, 8K, y HDR)",
                            Stock = 16
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Microsoft",
                            Description = "Consola casi buena",
                            Discount = 22,
                            Name = "Xbox 360",
                            Price = 265m,
                            PrincipalImageURL = "https://i.ebayimg.com/images/g/oBUAAOSwVgljSZS8/s-l400.jpg",
                            ProductId = 6,
                            ReleaseDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Specifications = "CPU: IBM PowerPC Tri-Core Xenon a 3.2GHz; GPU: ATI Xenos, 240 GFLOPs; Memoria: 512 MB GDDR3 a 700 MHz; Almacenamiento: Disco duro de 20 GB/60 GB/120 GB (según modelo); Peso: Aprox. 3.5 Kg; Entrada/Salida: 3 puertos USB 2.0; Red: 1 puerto Ethernet (10/100), Wi-Fi opcional con adaptador externo (en modelos antiguos); Alimentación: AC 100-240V, 50/60Hz; Consumo de energía: Aprox. 175W; Salida AV: Salida HDMI™, Salida por componentes, Salida por cable AV estándar",
                            Stock = 5
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            Name = "RPG"
                        },
                        new
                        {
                            GenderId = 2,
                            Name = "Shooter"
                        },
                        new
                        {
                            GenderId = 3,
                            Name = "Estrategia"
                        },
                        new
                        {
                            GenderId = 4,
                            Name = "Accion"
                        },
                        new
                        {
                            GenderId = 5,
                            Name = "Deportes"
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlatformId");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            PlatformId = 1,
                            Name = "Steam"
                        },
                        new
                        {
                            PlatformId = 2,
                            Name = "Play Station"
                        },
                        new
                        {
                            PlatformId = 3,
                            Name = "Xbox"
                        },
                        new
                        {
                            PlatformId = 4,
                            Name = "Switch"
                        },
                        new
                        {
                            PlatformId = 5,
                            Name = "Ubisoft"
                        },
                        new
                        {
                            PlatformId = 6,
                            Name = "Epic Games"
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Sales")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Sales = 50
                        },
                        new
                        {
                            Id = 2,
                            Sales = 44
                        },
                        new
                        {
                            Id = 3,
                            Sales = 22
                        },
                        new
                        {
                            Id = 4,
                            Sales = 4
                        },
                        new
                        {
                            Id = 5,
                            Sales = 141
                        },
                        new
                        {
                            Id = 6,
                            Sales = 967
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.SecondHandProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("SecondHandProducts");
                });

            modelBuilder.Entity("GamingCorner.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "C/ La Lectura",
                            Admin = true,
                            Email = "diego@gmail.com",
                            Name = "Diego",
                            Password = "12345",
                            PhoneNumber = "601112734"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "Avda. San Juan de la Peña",
                            Admin = true,
                            Email = "ivan@gmail.com",
                            Name = "Ivan",
                            Password = "12345",
                            PhoneNumber = "123456789"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "El Actur",
                            Admin = false,
                            Email = "adrian@gmail.com",
                            Name = "Adrian",
                            Password = "00000",
                            PhoneNumber = "987654321"
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Videogame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Distributor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pegi")
                        .HasColumnType("int");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrincipalImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Requisitos1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requisitos2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Videogames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Juego de rol y acción en mundo abierto",
                            Developer = "FromSoftware",
                            Discount = 0,
                            Distributor = "Bandai Namco",
                            Name = "Elden Ring",
                            Pegi = 18,
                            Price = 59.99m,
                            PrincipalImageURL = "https://upload.wikimedia.org/wikipedia/en/9/9c/Elden_Ring_Box_art.jpg",
                            ProductId = 1,
                            ReleaseDate = new DateTime(2022, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Requisitos1 = "Intel Core i5-8400 / AMD Ryzen 3 3300X",
                            Requisitos2 = "12 GB RAM, GTX 1060 3GB / Radeon RX 580",
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Acción y aventura con mitología nórdica",
                            Developer = "Santa Monica Studio",
                            Discount = 5,
                            Distributor = "Sony Interactive Entertainment",
                            Name = "God of War Ragnarök",
                            Pegi = 18,
                            Price = 69.99m,
                            PrincipalImageURL = "https://upload.wikimedia.org/wikipedia/en/9/9e/God_of_War_Ragnar%C3%B6k_cover.jpg",
                            ProductId = 2,
                            ReleaseDate = new DateTime(2022, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Stock = 75
                        },
                        new
                        {
                            Id = 3,
                            Description = "RPG ambientado en el mundo de Harry Potter",
                            Developer = "Portkey Games",
                            Discount = 10,
                            Distributor = "Warner Bros. Games",
                            Name = "Hogwarts Legacy",
                            Pegi = 16,
                            Price = 49.99m,
                            PrincipalImageURL = "https://upload.wikimedia.org/wikipedia/en/7/76/Hogwarts_Legacy_cover.jpg",
                            ProductId = 3,
                            ReleaseDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Requisitos1 = "Intel Core i5-6600 / AMD Ryzen 5 1400",
                            Requisitos2 = "16 GB RAM, GTX 1070 / RX Vega 56",
                            Stock = 80
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.VideogameGender", b =>
                {
                    b.Property<int>("VideogameId")
                        .HasColumnType("int");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.HasKey("VideogameId", "GenderId");

                    b.HasIndex("GenderId");

                    b.ToTable("VideogameGenders");

                    b.HasData(
                        new
                        {
                            VideogameId = 1,
                            GenderId = 1
                        },
                        new
                        {
                            VideogameId = 1,
                            GenderId = 2
                        },
                        new
                        {
                            VideogameId = 2,
                            GenderId = 2
                        },
                        new
                        {
                            VideogameId = 2,
                            GenderId = 3
                        },
                        new
                        {
                            VideogameId = 3,
                            GenderId = 1
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Console", b =>
                {
                    b.HasOne("GamingCorner.Models.Platform", null)
                        .WithMany("Consoles")
                        .HasForeignKey("PlatformId");

                    b.HasOne("GamingCorner.Models.Product", "Product")
                        .WithOne("Console")
                        .HasForeignKey("GamingCorner.Models.Console", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GamingCorner.Models.SecondHandProduct", b =>
                {
                    b.HasOne("GamingCorner.Models.Product", "Product")
                        .WithOne("SecondHandProduct")
                        .HasForeignKey("GamingCorner.Models.SecondHandProduct", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GamingCorner.Models.Videogame", b =>
                {
                    b.HasOne("GamingCorner.Models.Platform", null)
                        .WithMany("videogames")
                        .HasForeignKey("PlatformId");

                    b.HasOne("GamingCorner.Models.Product", "Product")
                        .WithOne("Videogame")
                        .HasForeignKey("GamingCorner.Models.Videogame", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamingCorner.Models.User", null)
                        .WithMany("Videogames")
                        .HasForeignKey("UserId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GamingCorner.Models.VideogameGender", b =>
                {
                    b.HasOne("GamingCorner.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingCorner.Models.Videogame", "Videogame")
                        .WithMany()
                        .HasForeignKey("VideogameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("GamingCorner.Models.Platform", b =>
                {
                    b.Navigation("Consoles");

                    b.Navigation("videogames");
                });

            modelBuilder.Entity("GamingCorner.Models.Product", b =>
                {
                    b.Navigation("Console");

                    b.Navigation("SecondHandProduct");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("GamingCorner.Models.User", b =>
                {
                    b.Navigation("Videogames");
                });
#pragma warning restore 612, 618
        }
    }
}
