// <auto-generated />
using System;
using GamingCorner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingCorner.Data.Migrations
{
    [DbContext(typeof(GamingCornerContext))]
    partial class GamingCornerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GamingCorner.Models.Console_", b =>
                {
                    b.Property<int>("ConsoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsoleId"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ConsoleId");

                    b.HasIndex("PlatformId");

                    b.ToTable("Consoles");

                    b.HasData(
                        new
                        {
                            ConsoleId = 1,
                            Available = true,
                            ImageURL = "https://gmedia.playstation.com/is/image/SIEPDC/ps4-pro-product-thumbnail-01-en-14sep21",
                            Name = "Play Station 4",
                            PlatformId = 1,
                            Price = 300m,
                            Specifications = "CPU:AMD 'Jaguar' x86-64, 8 núcleos; GPU: motor gráfico AMD de 1,84 TFLOPS basado en Radeon; Memoria:8 GB GDDR5; Almacenamiento:1 TB; Peso: Aprox. 2,1 Kg; Entrada/Salida:2 puertos de altísima velocidad USB (USB 3.1 Gen1) y 1 puerto AUX; Red:1 puerto Ethernet (10BASE-T, 100BASE-TX, 1000BASE-T) / IEEE 802.11 a/b/g/n/ac / Bluetooth® 4.0; Alimentacion:AC de 100-240 V, 50/60 Hz; Consumo de energia: 165W; Salida AV:Salida HDMI™ (compatible con salida HDR)",
                            Stock = 16
                        },
                        new
                        {
                            ConsoleId = 2,
                            Available = true,
                            ImageURL = "https://m.media-amazon.com/images/I/51f6iZlNnvL.jpg",
                            Name = "Play Station 5",
                            PlatformId = 1,
                            Price = 490m,
                            Specifications = "CPU: AMD Ryzen Zen 2, 8 núcleos a 3.5GHz; GPU: AMD RDNA 2, 10.28 TFLOPs, 36 CUs a 2.23GHz; Memoria: 16 GB GDDR6; Almacenamiento: SSD personalizado de 825 GB; Peso: Aprox. 4.5 Kg; Entrada/Salida: 2 puertos USB de alta velocidad (USB 3.1 Gen2), 1 puerto USB-C; Red: 1 puerto Ethernet (10BASE-T, 100BASE-TX, 1000BASE-T), Wi-Fi 6 (802.11ax), Bluetooth® 5.1; Alimentación: AC 100-240V, 50/60Hz; Consumo de energía: 350W; Salida AV: Salida HDMI™ 2.1 (compatible con 4K a 120Hz, 8K, y HDR)",
                            Stock = 16
                        },
                        new
                        {
                            ConsoleId = 3,
                            Available = true,
                            ImageURL = "https://i.ebayimg.com/images/g/oBUAAOSwVgljSZS8/s-l400.jpg",
                            Name = "Xbox 360",
                            PlatformId = 3,
                            Price = 265m,
                            Specifications = "CPU: IBM PowerPC Tri-Core Xenon a 3.2GHz; GPU: ATI Xenos, 240 GFLOPs; Memoria: 512 MB GDDR3 a 700 MHz; Almacenamiento: Disco duro de 20 GB/60 GB/120 GB (según modelo); Peso: Aprox. 3.5 Kg; Entrada/Salida: 3 puertos USB 2.0; Red: 1 puerto Ethernet (10/100), Wi-Fi opcional con adaptador externo (en modelos antiguos); Alimentación: AC 100-240V, 50/60Hz; Consumo de energía: Aprox. 175W; Salida AV: Salida HDMI™, Salida por componentes, Salida por cable AV estándar",
                            Stock = 5
                        },
                        new
                        {
                            ConsoleId = 4,
                            Available = true,
                            ImageURL = "https://m.media-amazon.com/images/I/61nq7mC0tHL._AC_UF894,1000_QL80_.jpg",
                            Name = "Xbox Series X",
                            PlatformId = 3,
                            Price = 500m,
                            Specifications = "CPU: AMD Ryzen Zen 2, 8 núcleos a 3.8GHz (3.6GHz con SMT); GPU: AMD RDNA 2, 12 TFLOPs, 52 CUs a 1.825GHz; Memoria: 16 GB GDDR6; Almacenamiento: SSD NVMe personalizado de 1 TB; Peso: Aprox. 4.45 Kg; Entrada/Salida: 3 puertos USB 3.1 Gen1; Red: 1 puerto Ethernet (10/100/1000), Wi-Fi 5 (802.11ac), Bluetooth®; Alimentación: AC 100-240V, 50/60Hz; Consumo de energía: Aprox. 315W; Salida AV: Salida HDMI™ 2.1 (compatible con 4K a 120Hz, 8K, y HDR)",
                            Stock = 8
                        },
                        new
                        {
                            ConsoleId = 5,
                            Available = true,
                            ImageURL = "https://img.pccomponentes.com/articles/23/233482/consola-nintendo-switch-1351124-81-l.jpg",
                            Name = "Nintendo Switch",
                            PlatformId = 4,
                            Price = 280m,
                            Specifications = "CPU: NVIDIA Custom Tegra Processor; GPU: NVIDIA GPU basada en arquitectura Maxwell; Memoria: 4 GB LPDDR4; Almacenamiento: 32 GB de almacenamiento interno (expandible mediante tarjeta microSD hasta 2 TB); Peso: Aprox. 0.88 Kg (con Joy-Con); Entrada/Salida: 1 puerto USB Type-C (para carga), 1 puerto para cartuchos de juego, ranura para tarjeta microSD; Red: Wi-Fi 802.11 a/b/g/n/ac, Bluetooth® 4.1, Soporte LAN con adaptador (vía base de acoplamiento); Alimentación: Batería interna de ion de litio de 4310mAh, cargador AC 100-240V; Consumo de energía: Aprox. 18W (en modo portátil); Salida AV: Salida HDMI™ (modo TV, hasta 1080p), pantalla de 6.2 pulgadas LCD (1280x720 en modo portátil)",
                            Stock = 6
                        },
                        new
                        {
                            ConsoleId = 6,
                            Available = true,
                            ImageURL = "https://img.pccomponentes.com/articles/22/224445/1.jpg",
                            Name = "Nintendo Switch Lite",
                            PlatformId = 4,
                            Price = 160m,
                            Specifications = "CPU: NVIDIA Custom Tegra Processor; GPU: NVIDIA GPU basada en arquitectura Maxwell; Memoria: 4 GB LPDDR4; Almacenamiento: 32 GB de almacenamiento interno (expandible mediante tarjeta microSD hasta 2 TB); Peso: Aprox. 0.275 Kg; Entrada/Salida: 1 puerto USB Type-C (para carga), 1 puerto para cartuchos de juego, ranura para tarjeta microSD; Red: Wi-Fi 802.11 a/b/g/n/ac, Bluetooth® 4.1; Alimentación: Batería interna de ion de litio de 3570mAh, cargador AC 100-240V; Consumo de energía: Aprox. 13.5W (en modo portátil); Salida AV: Pantalla de 5.5 pulgadas LCD (1280x720), sin salida HDMI (solo modo portátil)",
                            Stock = 10
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            Name = "RPG"
                        },
                        new
                        {
                            GenderId = 2,
                            Name = "Shooter"
                        },
                        new
                        {
                            GenderId = 3,
                            Name = "Estrategia"
                        },
                        new
                        {
                            GenderId = 4,
                            Name = "Accion"
                        },
                        new
                        {
                            GenderId = 5,
                            Name = "Deportes"
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Platform", b =>
                {
                    b.Property<int>("PlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlatformId"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlatformId");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            PlatformId = 1,
                            Name = "Steam"
                        },
                        new
                        {
                            PlatformId = 2,
                            Name = "Play Station"
                        },
                        new
                        {
                            PlatformId = 3,
                            Name = "Xbox"
                        },
                        new
                        {
                            PlatformId = 4,
                            Name = "Switch"
                        },
                        new
                        {
                            PlatformId = 5,
                            Name = "Ubisoft"
                        },
                        new
                        {
                            PlatformId = 6,
                            Name = "Epic Games"
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Available = true,
                            Description = "COD Infinite Warfare nuevo en perfectas condiciones y con su precinto",
                            ImageURL = "https://cdn.wallapop.com/images/10420/g2/d9/__/c10420p971437424/i4694537666.jpg?pictureSize=W640",
                            Name = "COD nuevo",
                            Price = 15m
                        },
                        new
                        {
                            ProductId = 2,
                            Available = true,
                            Description = "Juego casi nuevo",
                            ImageURL = "https://secondbest.es/wp-content/uploads/2024/08/Photoroom-20240823_175759_1.webp",
                            Name = "Uncharted",
                            Price = 10m
                        },
                        new
                        {
                            ProductId = 3,
                            Available = true,
                            Description = "Practicamente nuevo",
                            ImageURL = "https://images.milanuncios.com/api/v1/ma-ad-media-pro/images/69f02b50-a035-4b00-a96b-184ba7a061d1?rule=hw396_70",
                            Name = "Dark Souls",
                            Price = 7m
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"), 1L, 1);

                    b.Property<int?>("ConsoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VideogameId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("ConsoleId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("VideogameId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Date = new DateTime(2025, 5, 6, 19, 41, 14, 860, DateTimeKind.Local).AddTicks(2299),
                            ProductId = 1,
                            Type = "Compra",
                            UserId = 1
                        },
                        new
                        {
                            TransactionId = 2,
                            Date = new DateTime(2025, 5, 6, 19, 41, 14, 860, DateTimeKind.Local).AddTicks(2335),
                            ProductId = 2,
                            Type = "Compra",
                            UserId = 2
                        },
                        new
                        {
                            TransactionId = 3,
                            Date = new DateTime(2025, 5, 6, 19, 41, 14, 860, DateTimeKind.Local).AddTicks(2337),
                            ProductId = 3,
                            Type = "Compra",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "C/ La Lectura",
                            Admin = true,
                            Email = "diego@gmail.com",
                            Name = "Diego",
                            Password = "12345",
                            PhoneNumber = "601112734"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "Avda. San Juan de la Peña",
                            Admin = true,
                            Email = "ivan@gmail.com",
                            Name = "Ivan",
                            Password = "12345",
                            PhoneNumber = "123456789"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "El Actur",
                            Admin = false,
                            Email = "adrian@gmail.com",
                            Name = "Adrian",
                            Password = "00000",
                            PhoneNumber = "987654321"
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Videogame", b =>
                {
                    b.Property<int>("VideogameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideogameId"), 1L, 1);

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pegi")
                        .HasColumnType("int");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Requisitos1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requisitos2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("VideogameId");

                    b.HasIndex("GenderId");

                    b.HasIndex("PlatformId");

                    b.HasIndex("UserId");

                    b.ToTable("Videogames");

                    b.HasData(
                        new
                        {
                            VideogameId = 1,
                            Available = true,
                            Code = "code1",
                            Description = "Rocket League es un videojuego que combina fútbol con vehículos propulsados por cohetes, desarrollado por Psyonix. Los jugadores controlan autos que pueden saltar y volar brevemente para golpear un balón gigante e intentar marcar goles en la portería del equipo contrario. El juego cuenta con modos tanto en solitario como multijugador, tanto en línea como local, y ofrece partidas competitivas y casuales. Con su jugabilidad rápida, mecánicas simples pero desafiantes, y una comunidad activa, Rocket League se ha convertido en un fenómeno popular en el mundo de los eSports y el gaming casual.",
                            GenderId = 1,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co5w0w.webp",
                            Name = "Rocket League",
                            Pegi = 12,
                            PlatformId = 1,
                            Price = 15m,
                            Requisitos1 = "Windows 7; Intel Core 2 Duo E4600; 2 GB RAM; NVIDIA GeForce 8800; 7 GB disponibles; 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i5-2550K; Memoria: 4 GB RAM; Gráfica: NVIDIA GeForce GTX 660; Almacenamiento: 7 GB disponibles; DirectX: 11",
                            Stock = 3,
                            UserId = 1
                        },
                        new
                        {
                            VideogameId = 2,
                            Available = true,
                            Code = "code2",
                            Description = "Grand Theft Auto V (GTA 5) es un juego de acción y aventura en mundo abierto desarrollado por Rockstar Games, ambientado en la ciudad ficticia de Los Santos, basada en Los Ángeles. La historia sigue a tres personajes: Michael, un ex ladrón de bancos; Franklin, un joven ambicioso; y Trevor, un ex compañero de Michael con tendencias violentas. Juntos realizan una serie de atracos mientras enfrentan problemas con el gobierno y pandillas. El juego ofrece libertad para explorar, realizar misiones, y participar en actividades variadas, además de contar con un modo en línea multijugador llamado GTA Online.",
                            GenderId = 2,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1twh.webp",
                            Name = "GTA 5",
                            Pegi = 18,
                            PlatformId = 2,
                            Price = 13m,
                            Requisitos1 = "Windows 7; Procesador: Intel Core 2 Quad CPU Q6600; Memoria: 4 GB RAM; Gráfica: NVIDIA 9800 GT; Almacenamiento: 72 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i5 3470; Memoria: 8 GB RAM; Gráfica: NVIDIA GTX 660 2GB; Almacenamiento: 72 GB disponibles; DirectX: 11",
                            Stock = 7,
                            UserId = 1
                        },
                        new
                        {
                            VideogameId = 3,
                            Available = true,
                            Code = "code3",
                            Description = "The Witcher 3: Wild Hunt es un juego de rol de acción desarrollado por CD Projekt Red, basado en las novelas de Andrzej Sapkowski. Los jugadores asumen el papel de Geralt de Rivia, un cazador de monstruos conocido como brujo, mientras recorre un vasto mundo abierto lleno de misiones, criaturas, y personajes complejos. La historia principal sigue a Geralt en su búsqueda por encontrar a su hija adoptiva, Ciri, mientras el continente está envuelto en conflictos políticos y la amenaza de la mítica Cacería Salvaje. Con su narrativa profunda, sistema de combate dinámico, y un mundo detallado lleno de decisiones morales, The Witcher 3 es considerado uno de los mejores videojuegos de todos los tiempos.",
                            GenderId = 3,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lgo.webp",
                            Name = "The Witcher 3",
                            Pegi = 18,
                            PlatformId = 3,
                            Price = 20m,
                            Requisitos1 = "Windows 7; Procesador: Intel Core i5-2500K; Memoria: 6 GB RAM; Gráfica: NVIDIA GeForce GTX 660; Almacenamiento: 35 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i7 3770; Memoria: 8 GB RAM; Gráfica: NVIDIA GeForce GTX 770; Almacenamiento: 35 GB disponibles; DirectX: 12",
                            Stock = 5,
                            UserId = 2
                        },
                        new
                        {
                            VideogameId = 4,
                            Available = true,
                            Code = "code4",
                            Description = "Minecraft es un videojuego de construcción y supervivencia desarrollado por Mojang Studios. En un mundo abierto y generado de manera procedural, los jugadores pueden recolectar recursos, construir estructuras, explorar cuevas y combatir criaturas mientras gestionan su supervivencia. El juego cuenta con varios modos, como el modo supervivencia, donde los jugadores deben gestionar su salud y hambre, y el modo creativo, que ofrece recursos ilimitados para la construcción libre. Con su estilo gráfico de bloques y su libertad casi infinita para crear, Minecraft se ha convertido en uno de los juegos más influyentes y vendidos de todos los tiempos, con una gran comunidad y mods que amplían su jugabilidad.",
                            GenderId = 4,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co2b4k.webp",
                            Name = "Minecraft",
                            Pegi = 7,
                            PlatformId = 1,
                            Price = 25m,
                            Requisitos1 = "Windows 7; Procesador: Intel Core i3-3210; Memoria: 4 GB RAM; Gráfica: Intel HD Graphics 4000; Almacenamiento: 1 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i5-4690; Memoria: 8 GB RAM; Gráfica: NVIDIA GTX 960; Almacenamiento: 4 GB disponibles; DirectX: 12",
                            Stock = 10,
                            UserId = 3
                        },
                        new
                        {
                            VideogameId = 5,
                            Available = true,
                            Code = "code5",
                            Description = "Fortnite es un videojuego multijugador en línea desarrollado por Epic Games, conocido principalmente por su modo Battle Royale, donde 100 jugadores compiten en una isla para ser el último en pie. Los jugadores deben recolectar armas, materiales para construir estructuras, y sobrevivir a una tormenta que reduce el área jugable. Con su jugabilidad rápida, gráficos coloridos, y la capacidad de construir estructuras defensivas durante los combates, Fortnite ha ganado una enorme popularidad a nivel mundial. El juego también cuenta con otros modos, como Salva el Mundo (un modo cooperativo) y Creativo, donde los jugadores pueden diseñar sus propios mundos.",
                            GenderId = 5,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ekt.webp",
                            Name = "Fortnite",
                            Pegi = 12,
                            PlatformId = 2,
                            Price = 0m,
                            Requisitos1 = "OS: Windows 7; Procesador: Intel Core i3-3225; Memoria: 4 GB RAM; Gráfica: Intel HD 4000; Almacenamiento: 15 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i5-7300U; Memoria: 8 GB RAM; Gráfica: NVIDIA GTX 960; Almacenamiento: 15 GB disponibles; DirectX: 12",
                            Stock = 8,
                            UserId = 2
                        },
                        new
                        {
                            VideogameId = 6,
                            Available = true,
                            Code = "code6",
                            Description = "Overwatch es un juego de disparos en primera persona basado en equipos, desarrollado por Blizzard Entertainment. En el juego, los jugadores eligen entre una amplia gama de personajes, conocidos como héroes, cada uno con habilidades únicas y roles específicos dentro del equipo (daño, tanque, o apoyo). Los equipos de seis jugadores compiten en diversos modos de juego que incluyen capturar objetivos o escoltar cargas a lo largo de mapas detallados. Overwatch destaca por su enfoque en el trabajo en equipo, su jugabilidad rápida y accesible, y su elenco diverso de personajes, lo que lo ha convertido en uno de los títulos más populares en el ámbito de los eSports y los juegos multijugador.",
                            GenderId = 1,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co7v86.webp",
                            Name = "Overwatch",
                            Pegi = 12,
                            PlatformId = 3,
                            Price = 30m,
                            Requisitos1 = "Windows 7; Procesador: Intel Core i3; Memoria: 4 GB RAM; Gráfica: NVIDIA GeForce GTX 460; Almacenamiento: 30 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i5; Memoria: 6 GB RAM; Gráfica: NVIDIA GeForce GTX 660; Almacenamiento: 30 GB disponibles; DirectX: 12",
                            Stock = 6,
                            UserId = 1
                        },
                        new
                        {
                            VideogameId = 7,
                            Available = true,
                            Code = "code7",
                            Description = "FIFA 21 es un simulador de fútbol desarrollado por EA Sports, parte de la popular franquicia FIFA. El juego ofrece modos de juego variados, desde partidos rápidos hasta competiciones completas, incluyendo FIFA Ultimate Team (FUT), donde los jugadores pueden crear y gestionar su propio equipo con cartas de futbolistas reales, y el Modo Carrera, que permite dirigir un equipo o un jugador a lo largo de varias temporadas. Con mejoras en la jugabilidad, gráficos realistas y una amplia lista de equipos y ligas con licencias oficiales, FIFA 21 busca ofrecer una experiencia auténtica de fútbol tanto en modos en solitario como en multijugador en línea.",
                            GenderId = 2,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wm2.webp",
                            Name = "FIFA 21",
                            Pegi = 3,
                            PlatformId = 1,
                            Price = 50m,
                            Requisitos1 = "OS: Windows 7; Procesador: Intel Core i3-6100; Memoria: 8 GB RAM; Gráfica: NVIDIA GTX 660; Almacenamiento: 50 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel i5-3550; Memoria: 8 GB RAM; Gráfica: NVIDIA GeForce GTX 670; Almacenamiento: 50 GB disponibles; DirectX: 12",
                            Stock = 12,
                            UserId = 2
                        },
                        new
                        {
                            VideogameId = 8,
                            Available = true,
                            Code = "code8",
                            Description = "Cyberpunk 2077 es un juego de rol de acción desarrollado por CD Projekt Red, ambientado en un futuro distópico en la metrópolis de Night City. Los jugadores controlan a V, un mercenario personalizable que puede mejorar sus habilidades con implantes cibernéticos, mientras navega por un mundo abierto lleno de corporaciones corruptas, bandas criminales y tecnología avanzada. El juego ofrece una narrativa profunda con decisiones que impactan la historia, un sistema de combate variado que incluye armas de fuego y habilidades cuerpo a cuerpo, y una rica personalización de personajes. A pesar de su lanzamiento inicial con algunos problemas técnicos, Cyberpunk 2077 ha sido elogiado por su inmersivo diseño de mundo, historia y libertad de juego.",
                            GenderId = 3,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co64re.webp",
                            Name = "Cyberpunk 2077",
                            Pegi = 18,
                            PlatformId = 2,
                            Price = 60m,
                            Requisitos1 = "Windows 7; Procesador: Intel Core i5-3570K; Memoria: 8 GB RAM; Gráfica: NVIDIA GTX 780; Almacenamiento: 70 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i7-4790; Memoria: 12 GB RAM; Gráfica: NVIDIA RTX 2060; Almacenamiento: 70 GB disponibles; DirectX: 12",
                            Stock = 4,
                            UserId = 3
                        },
                        new
                        {
                            VideogameId = 9,
                            Available = true,
                            Code = "code9",
                            Description = "Red Dead Redemption 2 es un juego de acción y aventura desarrollado por Rockstar Games, ambientado en el salvaje oeste de Estados Unidos a finales del siglo XIX. Los jugadores asumen el papel de Arthur Morgan, un forajido miembro de la banda de Dutch van der Linde, mientras lucha por sobrevivir en un mundo cambiante donde la ley y el orden están comenzando a imponerse. El juego ofrece un vasto mundo abierto con una atención meticulosa a los detalles, permitiendo a los jugadores cazar, pescar, interactuar con personajes y tomar decisiones que afectan la narrativa. Con su trama profunda, personajes complejos y una jugabilidad inmersiva, Red Dead Redemption 2 ha sido aclamado como uno de los mejores videojuegos de todos los tiempos.",
                            GenderId = 4,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.webp",
                            Name = "Red Dead Redemption 2",
                            Pegi = 18,
                            PlatformId = 3,
                            Price = 40m,
                            Requisitos1 = "Windows 7; Procesador: Intel Core i5-2500K; Memoria: 8 GB RAM; Gráfica: NVIDIA GTX 770; Almacenamiento: 150 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i7-4770K; Memoria: 12 GB RAM; Gráfica: NVIDIA RTX 2060; Almacenamiento: 150 GB disponibles; DirectX: 12",
                            Stock = 9,
                            UserId = 3
                        },
                        new
                        {
                            VideogameId = 10,
                            Available = true,
                            Code = "code10",
                            Description = "Assassin's Creed Valhalla es un juego de acción y rol desarrollado por Ubisoft, ambientado en la época vikinga, específicamente durante la invasión de Inglaterra en el siglo IX. Los jugadores controlan a Eivor, un guerrero vikingo que lidera a su clan en busca de un nuevo hogar en tierras inglesas, mientras lidia con la lucha entre asesinos y templarios. El juego combina exploración en un vasto mundo abierto, combates brutales, y la posibilidad de desarrollar asentamientos. Con un enfoque en la personalización de personajes, combate táctico y narrativas basadas en elecciones, Assassin's Creed Valhalla ofrece una experiencia inmersiva de la vida vikinga y sus incursiones.",
                            GenderId = 5,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rrw.webp",
                            Name = "Assassin's Creed Valhalla",
                            Pegi = 18,
                            PlatformId = 4,
                            Price = 55m,
                            Requisitos1 = "OS: Windows 7; Procesador: Intel Core i5-4460; Memoria: 8 GB RAM; Gráfica: NVIDIA GTX 960; Almacenamiento: 50 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i7-6700; Memoria: 12 GB RAM; Gráfica: NVIDIA RTX 2060; Almacenamiento: 50 GB disponibles; DirectX: 12",
                            Stock = 7,
                            UserId = 1
                        },
                        new
                        {
                            VideogameId = 11,
                            Available = true,
                            Code = "code11",
                            Description = "Call of Duty: Modern Warfare es un juego de disparos en primera persona desarrollado por Infinity Ward y publicado por Activision. Lanzado en 2019, es una reinvención del sub-franquicia Modern Warfare, y ofrece una campaña centrada en conflictos militares modernos y operaciones encubiertas en el Medio Oriente y Europa. Los jugadores asumen el rol de personajes como Captain Price y un equipo de soldados de élite que luchan contra grupos terroristas y fuerzas enemigas. Además de su intensa campaña, el juego incluye modos multijugador competitivos y el popular modo Warzone, que introduce el formato battle royale. Con gráficos realistas, jugabilidad táctica y un enfoque en la narrativa cruda y madura, Modern Warfare ha sido aclamado tanto por su campaña como por su multijugador.",
                            GenderId = 1,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rsg.webp",
                            Name = "Call of Duty: Modern Warfare",
                            Pegi = 18,
                            PlatformId = 4,
                            Price = 50m,
                            Requisitos1 = "Windows 7; Procesador: Intel Core i3-4340; Memoria: 8 GB RAM; Gráfica: NVIDIA GTX 670; Almacenamiento: 175 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i7-6700; Memoria: 12 GB RAM; Gráfica: NVIDIA RTX 2070; Almacenamiento: 175 GB disponibles; DirectX: 12",
                            Stock = 11,
                            UserId = 1
                        },
                        new
                        {
                            VideogameId = 12,
                            Available = true,
                            Code = "code12",
                            Description = "Horizon Zero Dawn es un juego de rol y acción desarrollado por Guerrilla Games. Ambientado en un futuro postapocalíptico donde las máquinas dominan la Tierra, los jugadores controlan a Aloy, una joven cazadora en busca de respuestas sobre su origen y el mundo que la rodea. La historia sigue a Aloy mientras explora vastos paisajes abiertos, lucha contra criaturas robóticas, y descubre los secretos de una civilización perdida. El juego combina combate estratégico, donde los jugadores deben usar trampas, armas y habilidades para derrotar a las máquinas, con una narrativa profunda y visualmente impresionante. Horizon Zero Dawn ha sido elogiado por su mundo inmersivo, mecánicas de combate innovadoras y la protagonista carismática.",
                            GenderId = 2,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co2una.webp",
                            Name = "Horizon Zero Dawn",
                            Pegi = 16,
                            PlatformId = 4,
                            Price = 35m,
                            Requisitos1 = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Requisitos2 = "RTX 3060;MUCHAS COSAS MAS; LAS TERCERA COSA; Y UNA DE REGALO",
                            Stock = 5,
                            UserId = 2
                        },
                        new
                        {
                            VideogameId = 13,
                            Available = true,
                            Code = "code13",
                            Description = "Stardew Valley es un juego de simulación de granja desarrollado por ConcernedApe. Los jugadores asumen el papel de un personaje que hereda una granja en mal estado y deben restaurarla plantando cultivos, criando animales, pescando, y explorando minas en busca de recursos. Además de las actividades agrícolas, el juego incluye elementos de interacción social con los habitantes de la cercana Pelican Town, lo que permite a los jugadores formar amistades e incluso casarse. Con su estilo retro pixelado, jugabilidad relajante y libertad para gestionar la granja a su propio ritmo, Stardew Valley se ha convertido en un juego indie muy popular por su encanto, profundidad y capacidad de personalización.",
                            GenderId = 3,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/xrpmydnu9rpxvxfjkiu7.webp",
                            Name = "Stardew Valley",
                            Pegi = 7,
                            PlatformId = 4,
                            Price = 20m,
                            Requisitos1 = "OS: Windows 7; Procesador: Intel Core i5-2500K; Memoria: 8 GB RAM; Gráfica: NVIDIA GTX 780; Almacenamiento: 100 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i7-4770K; Memoria: 16 GB RAM; Gráfica: NVIDIA RTX 2060; Almacenamiento: 100 GB disponibles; DirectX: 12",
                            Stock = 8,
                            UserId = 2
                        },
                        new
                        {
                            VideogameId = 14,
                            Available = true,
                            Code = "code14",
                            Description = "Among Us es un juego multijugador en línea desarrollado por InnerSloth, en el que los jugadores deben trabajar juntos para completar tareas en una nave espacial, estación o base, mientras un grupo de impostores intenta sabotear la misión y eliminar a los demás jugadores. Los jugadores asumen uno de dos roles: tripulantes, que deben realizar tareas y descubrir a los impostores, o impostores, que deben sabotear y eliminar a los tripulantes sin ser descubiertos. Con su jugabilidad basada en la deducción social y las reuniones donde los jugadores discuten quién puede ser el impostor, Among Us se ha vuelto enormemente popular por su enfoque en la colaboración, traición y estrategia.",
                            GenderId = 4,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co6kqt.webp",
                            Name = "Among Us",
                            Pegi = 10,
                            PlatformId = 1,
                            Price = 5m,
                            Requisitos1 = "OS: Windows 7; Procesador: Intel Pentium 4; Memoria: 1 GB RAM; Gráfica: NVIDIA GeForce 6100; Almacenamiento: 250 MB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i3-6100; Memoria: 2 GB RAM; Gráfica: NVIDIA GTX 660; Almacenamiento: 250 MB disponibles; DirectX: 12",
                            Stock = 15,
                            UserId = 2
                        },
                        new
                        {
                            VideogameId = 15,
                            Available = true,
                            Code = "code15",
                            Description = "The Legend of Zelda: Breath of the Wild es un juego de acción y aventura desarrollado por Nintendo, ambientado en el vasto reino abierto de Hyrule. Los jugadores controlan a Link, quien despierta de un largo sueño para derrotar a Ganon, una antigua fuerza maligna que amenaza con destruir el reino. El juego destaca por su enfoque en la exploración, permitiendo a los jugadores escalar montañas, nadar, y planear a través del mundo mientras resuelven puzles, enfrentan enemigos y descubren secretos. Con un sistema de físicas realista, libertad sin precedentes en la serie, y una narrativa ambiental rica, Breath of the Wild es considerado uno de los mejores videojuegos de todos los tiempos por su innovación y profundidad.",
                            GenderId = 5,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_small/co4n26.png",
                            Name = "The Legend of Zelda: Breath of the Wild",
                            Pegi = 12,
                            PlatformId = 2,
                            Price = 60m,
                            Requisitos1 = "OS: Windows 7; Procesador: Intel Core i5-2400S; Memoria: 8 GB RAM; Gráfica: NVIDIA GTX 750; Almacenamiento: 40 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10; Procesador: Intel Core i7-4790; Memoria: 12 GB RAM; Gráfica: NVIDIA RTX 2060; Almacenamiento: 40 GB disponibles; DirectX: 12",
                            Stock = 6,
                            UserId = 3
                        },
                        new
                        {
                            VideogameId = 16,
                            Available = true,
                            Code = "code15",
                            Description = "God of War es un juego de acción y aventura desarrollado por Santa Monica Studio y publicado por Sony Interactive Entertainment. Lanzado en 2018, es una reinvención de la serie y sigue a Kratos, el dios de la guerra, en una nueva etapa de su vida en la mitología nórdica. Acompañado por su hijo Atreus, Kratos debe enfrentarse a poderosos enemigos y criaturas míticas mientras lidia con sus propios demonios internos y enseña a su hijo a sobrevivir en un mundo hostil. El juego combina combates intensos con una narrativa emocional, explorando temas de paternidad, redención y autodescubrimiento. Con su innovador sistema de combate, impresionantes gráficos y un mundo abierto lleno de secretos, God of War ha sido aclamado como uno de los mejores videojuegos de la historia.",
                            GenderId = 5,
                            ImageURL = "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tmu.webp",
                            Name = "God of War",
                            Pegi = 12,
                            PlatformId = 2,
                            Price = 60m,
                            Requisitos1 = "OS: Windows 10 (64 bits); Procesador: Intel i5-2500K (3.3 GHz) o AMD Ryzen 3 1200; Memoria: 8 GB RAM; Gráfica: NVIDIA GTX 960 (4 GB) o AMD R9 290X (4 GB); Almacenamiento: 70 GB disponibles; DirectX: 11",
                            Requisitos2 = "OS: Windows 10 (64 bits); Procesador: Intel i7-4770K (3.5 GHz) o AMD Ryzen 7 2700X; Memoria: 16 GB RAM; Gráfica: NVIDIA RTX 2060 (6 GB) o AMD RX 5700 XT (8 GB); Almacenamiento: 70 GB disponibles; DirectX: 12",
                            Stock = 6,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("GamingCorner.Models.Console_", b =>
                {
                    b.HasOne("GamingCorner.Models.Platform", "Platform")
                        .WithMany("Consoles")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GamingCorner.Models.Transaction", b =>
                {
                    b.HasOne("GamingCorner.Models.Console_", "Console")
                        .WithMany("Transactions")
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamingCorner.Models.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GamingCorner.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GamingCorner.Models.Videogame", "Videogame")
                        .WithMany("Transactions")
                        .HasForeignKey("VideogameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Console");

                    b.Navigation("Product");

                    b.Navigation("User");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("GamingCorner.Models.Videogame", b =>
                {
                    b.HasOne("GamingCorner.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingCorner.Models.Platform", "Platform")
                        .WithMany("videogames")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GamingCorner.Models.User", "User")
                        .WithMany("Videogames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Gender");

                    b.Navigation("Platform");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamingCorner.Models.Console_", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GamingCorner.Models.Platform", b =>
                {
                    b.Navigation("Consoles");

                    b.Navigation("videogames");
                });

            modelBuilder.Entity("GamingCorner.Models.Product", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("GamingCorner.Models.User", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("Videogames");
                });

            modelBuilder.Entity("GamingCorner.Models.Videogame", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
